name: flutter_radial_menu
description: A simple animated radial menu widget for Flutter.
version: 0.0.2
author: Rakor <rakor@vip.qq.com>
homepage: https://github.com/caopengfei/flutter_radial_menu

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=1.19.0 <3.0.0'
